import { DB } from "@/db";
import { product } from "../schema";
//import sampleData from "@/lib/sample-data";
//import { ProductModelType } from "../schema";

const shopProducts = {
  products: [
    {
      name: "Cross Body Ladies Bag Black",
      slug: "cross-body-ladies-bag-black",
      category: "Cross Body",
      description: "Classic style with modern comfort",
      images: [
        "/images/sample-products/1.webp",
        "/images/sample-products/2.webp",
        "/images/sample-products/3.webp",
      ],
      price: "59.99",
      brand: "Polo",
      rating: "4.5",
      numReviews: 10,
      stock: 100,
      isFeatured: true,
      banner: "/images/banner1.webp",
    },
    {
      name: "Cross Body Ladies Bag Brown",
      slug: "cross-body-ladies-bag-brown",
      category: "Cross Body",
      description: "Timeless style and premium comfort",
      images: [
        "/images/sample-products/4.webp",
        "/images/sample-products/5.webp",
        "/images/sample-products/6.webp",
      ],
      price: "85.9",
      brand: "Brooks Brothers",
      rating: "4.2",
      numReviews: 8,
      stock: 100,
      isFeatured: true,
      banner: "/images/banner2.webp",
    },
    {
      name: "Cross Body Ladies Bag Blue",
      slug: "cross-body-ladies-bag-blue",
      category: "Cross Body",
      description: "A perfect blend of sophistication and comfort",
      images: [
        "/images/sample-products/7.webp",
        "/images/sample-products/8.webp",
        "/images/sample-products/9.webp",
      ],
      price: "99.95",
      brand: "Tommy Hilfiger",
      rating: "4.9",
      numReviews: 3,
      stock: 100,
      isFeatured: true,
      banner: "/images/banner3.webp",
    },
    {
      name: "Tote Leather Work Bag Purse",
      slug: "tote-leather-work-bag-purse",
      category: "Tote Leather",
      description: "Streamlined design with flexible stretch",
      images: [
        "/images/sample-products/10.webp",
        "/images/sample-products/11.webp",
        "/images/sample-products/12.webp",
        "/images/sample-products/13.webp",
        "/images/sample-products/14.webp",
        "/images/sample-products/15.webp",
      ],
      price: "39.95",
      brand: "Calvin Klein",
      rating: "3.6",
      numReviews: 5,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Cross Body Small Single Strap Black",
      slug: "cross-body-small-single-strap-black",
      category: "Cross Body",
      description: "Iconic Polo design with refined oxford fabric",
      images: [
        "/images/sample-products/16.webp",
        "/images/sample-products/17.webp",
        "/images/sample-products/18.webp",
        "/images/sample-products/19.webp",
        "/images/sample-products/20.webp",
        "/images/sample-products/21.webp",
        "/images/sample-products/22.webp",
        "/images/sample-products/23.webp",
        "/images/sample-products/24.webp",
      ],
      price: "79.99",
      brand: "Polo",
      rating: "4.7",
      numReviews: 18,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Cross Body Double Strap Brown",
      slug: "cross-body-double-strap-brown",
      category: "Cross Body",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/25.webp",
        "/images/sample-products/26.webp",
      ],
      price: "99.99",
      brand: "Polo",
      rating: "4.6",
      numReviews: 12,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Cross Body Double Strap Black",
      slug: "cross-body-double-strap-black",
      category: "Cross Body",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/27.webp",
        "/images/sample-products/28.webp",
        "/images/sample-products/29.webp",
      ],
      price: "99.99",
      brand: "Polo",
      rating: "4.6",
      numReviews: 12,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Cross Body Chain Double Strap Brown",
      slug: "cross-body-double-chain-strap-brown",
      category: "Cross Chain",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/30.webp",
        "/images/sample-products/31.webp",
        "/images/sample-products/33.webp",
        "/images/sample-products/34.webp",
        "/images/sample-products/35.webp",
        "/images/sample-products/36.webp",
      ],
      price: "99.99",
      brand: "Polo",
      rating: "4.6",
      numReviews: 18,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Cross Body Single Strap Yellow",
      slug: "cross-body-single-strap-chain-yellow",
      category: "Cross Chain",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/37.webp",
        "/images/sample-products/38.webp",
        "/images/sample-products/39.webp",
      ],
      price: "99.99",
      brand: "Polo",
      rating: "4.6",
      numReviews: 18,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Single Belt Single Strap Brown",
      slug: "single-belt-single-strap-brown",
      category: "Single Belt",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/40.webp",
        "/images/sample-products/41.webp",
        "/images/sample-products/42.webp",
      ],
      price: "129.99",
      brand: "Polo",
      rating: "4.8",
      numReviews: 13,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Single Belt Single Strap Blue",
      slug: "single-belt-single-strap-blue",
      category: "Single Belt",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/43.webp",
        "/images/sample-products/44.webp",
        "/images/sample-products/45.webp",
      ],
      price: "129.99",
      brand: "Polo",
      rating: "4.8",
      numReviews: 18,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Single Belt Single Strap Cream",
      slug: "single-belt-single-strap-cream",
      category: "Single Belt",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/46.webp",
        "/images/sample-products/47.webp",
      ],
      price: "119.99",
      brand: "Polo",
      rating: "4.1",
      numReviews: 11,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Double Strap Single Chain Black Bag",
      slug: "double-strap-single-chain-black-bag",
      category: "Double Belt",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/48.webp",
        "/images/sample-products/49.webp",
        "/images/sample-products/50.webp",
        "/images/sample-products/51.webp",
        "/images/sample-products/52.webp",
        "/images/sample-products/53.webp",
      ],
      price: "112.99",
      brand: "Polo",
      rating: "4.5",
      numReviews: 21,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Cross Body Single Strap Purple",
      slug: "cross-body-single-strap-chain-purple",
      category: "Cross Chain",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/54.webp",
        "/images/sample-products/55.webp",
      ],
      price: "199.99",
      brand: "Polo",
      rating: "4.8",
      numReviews: 25,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Croc Leather Handbag Designer Series Natural",
      slug: "croc-leather-handbag-designer-series-natural",
      category: "Croc Designer",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/56.webp",
        "/images/sample-products/57.webp",
      ],
      price: "119.99",
      brand: "Polo",
      rating: "4.1",
      numReviews: 35,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Croc Leather Handbag Designer Series Cream",
      slug: "croc-leather-handbag-designer-series-cream",
      category: "Croc Designer",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/58.webp",
        "/images/sample-products/59.webp",
        "/images/sample-products/60.webp",
      ],
      price: "119.99",
      brand: "Polo",
      rating: "4.1",
      numReviews: 35,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Croc Leather Handbag Designer Series Purple",
      slug: "croc-leather-handbag-designer-series-purple",
      category: "Croc Designer",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/61.webp",
        "/images/sample-products/62.webp",
        "/images/sample-products/63.webp",
      ],
      price: "119.99",
      brand: "Polo",
      rating: "4.1",
      numReviews: 35,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Croc Leather Handbag Designer Series Blue",
      slug: "croc-leather-handbag-designer-series-blue",
      category: "Croc Designer",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/64.webp",
        "/images/sample-products/65.webp",
        "/images/sample-products/66.webp",
      ],
      price: "119.99",
      brand: "Polo",
      rating: "4.1",
      numReviews: 35,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Leather Style Tote Shoulder Handbag Violet",
      slug: "leather-style-tote-shoulder-handbag-violet",
      category: "Tote Leather",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/67.webp",
        "/images/sample-products/68.webp",
      ],
      price: "119.99",
      brand: "Polo",
      rating: "4.1",
      numReviews: 35,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Leather Style Tote Shoulder Handbag Black",
      slug: "leather-style-tote-shoulder-handbag-black",
      category: "Tote Leather",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/69.webp",
        "/images/sample-products/70.webp",
      ],
      price: "119.99",
      brand: "Polo",
      rating: "4.1",
      numReviews: 35,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Leather Style Tote Shoulder Handbag Brown",
      slug: "leather-style-tote-shoulder-handbag-brown",
      category: "Tote Leather",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/71.webp",
        "/images/sample-products/72.webp",
      ],
      price: "119.99",
      brand: "Polo",
      rating: "4.1",
      numReviews: 35,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Leather Style Tote Shoulder Handbag Pink",
      slug: "leather-style-tote-shoulder-handbag-pink",
      category: "Tote Leather",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/73.webp",
        "/images/sample-products/74.webp",
      ],
      price: "119.99",
      brand: "Polo",
      rating: "4.1",
      numReviews: 35,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Leather Style Tote Slouchy Handbag Black",
      slug: "leather-style-tote-slouchy-handbag-black",
      category: "Tote Leather",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/75.webp",
        "/images/sample-products/76.webp",
        "/images/sample-products/77.webp",
        "/images/sample-products/78.webp",
      ],
      price: "119.99",
      brand: "Polo",
      rating: "4.1",
      numReviews: 35,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Soft Leather Crossbody Multi Pocket Handbag",
      slug: "leather-style-tote-slouchy-handbag-multi-pocket",
      category: "Cross Body",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/79.webp",
        "/images/sample-products/80.webp",
        "/images/sample-products/81.webp",
      ],
      price: "119.99",
      brand: "Polo",
      rating: "4.1",
      numReviews: 35,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Top Handle Bucket Grab Shoulder Bag Green",
      slug: "top-handle-bucket-grab-shoulder-bag-green",
      category: "Cross Body",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/82.webp",
        "/images/sample-products/83.webp",
      ],
      price: "149.99",
      brand: "Polo",
      rating: "4.6",
      numReviews: 42,
      stock: 100,
      isFeatured: false,
      banner: null,
    },
  ],
};

export async function seed(db: DB) {
  await db.insert(product).values(shopProducts.products);
}
